name: Update Gradle Wrapper

on:
  schedule:
    # every week on Monday at 12pm
    - cron: "0 12 * * MON"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          base-branch: dev
          target-branch: dev